vsim1:
    username: admin
    password: password1
    ip: 192.168.1.1 
    device_type: alcatel_sros
    jumphost: jumphost1
7750sr1:
    username: admin
    password: password2
    ip: 192.168.1.2
    device_type: alcatel_sros
    global_delay_factor: 1
jumphost1:
    username: root
    password: password3
    ip: 192.168.1.3
    device_type: terminal_server
    global_delay_factor: 1
    ssh_command: ssh {username}@{ip}
    timeout: 90
    session_timeout: 600
